---
abstract: 'validate JSON against a schema'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
  - 'TOBYINK <tobyink@cpan.org>'
build_requires:
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords:
  - JSON
  - Schema
  - Validation
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Schema
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  JSON::Schema:
    file: lib/JSON/Schema.pm
    version: '0.016'
  JSON::Schema::Error:
    file: lib/JSON/Schema/Error.pm
    version: '0.016'
  JSON::Schema::Helper:
    file: lib/JSON/Schema/Helper.pm
    version: '0.016'
  JSON::Schema::Null:
    file: lib/JSON/Schema/Null.pm
    version: '0.016'
  JSON::Schema::Result:
    file: lib/JSON/Schema/Result.pm
    version: '0.016'
requires:
  HTTP::Link::Parser: '0.100'
  JSON: '2.00'
  JSON::Hyper: '0'
  JSON::Path: '0'
  LWP::UserAgent: '0'
  autovivification: '0'
  match::simple: '0'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/JSON-Schema/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-Schema
  homepage: https://metacpan.org/release/JSON-Schema
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/JSON-Schema/
version: '0.016'
x_contributors:
  - LIEUTAR
  - 'Markus Lauer'
  - TOBYINK
