---
abstract: 'validate JSON against a schema'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - JSON
  - Schema
  - Validation
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: JSON::Schema
name: JSON-Schema
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  HTTP::Link::Parser: 0.100
  JSON: 2.00
  JSON::Hyper: 0
  JSON::Path: 0
  LWP::UserAgent: 0
  autovivification: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=JSON-Schema
  homepage: https://metacpan.org/release/JSON-Schema
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/JSON-Schema/
version: 0.013
